#pragma once

#ifdef KEYBOARD_keebio_bdn9_rev1
#  define ENCODER_DIRECTION_FLIP
#  define BACKLIGHT_BREATHING
#endif

#define TAP_CODE_DELAY 20
#define TAPPING_TERM 300

// RGB
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
