#pragma once

#ifdef KEYBOARD_keebio_bdn9_rev1
#    define ENCODER_DIRECTION_FLIP
#    define BACKLIGHT_BREATHING
#endif

#define TAP_CODE_DELAY 20
#define TAPPING_TERM 300

// default to 5 dynamic keymap layers (VIA)
#define DYNAMIC_KEYMAP_LAYER_COUNT 5

// clear default RGB defines
#undef RGBLED_NUM
#undef RGBLIGHT_HUE_STEP
#undef RGBLIGHT_SAT_STEP
#undef RGBLIGHT_VAL_STEP
#undef RGBLIGHT_LIMIT_VAL
#undef RGBLIGHT_ANIMATIONS

// RGB
#define RGBLED_NUM 64
#define RGBLIGHT_LIMIT_VAL 225
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#define RGBLIGHT_LAYER_BLINK
#define RGBLIGHT_HUE_STEP 4
#define RGBLIGHT_SAT_STEP 4
#define RGBLIGHT_VAL_STEP 4

// RGB Animation Effects
//#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
//#define RGBLIGHT_EFFECT_KNIGHT
//#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
//#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_TWINKLE
