#pragma once

#ifdef KEYBOARD_keebio_bdn9_rev1
#  define ENCODER_DIRECTION_FLIP
#  define BACKLIGHT_BREATHING
#endif

#define TAP_CODE_DELAY 20
#define TAPPING_TERM 300

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

// LED STRIP
#undef RGBLED_NUM
#define RGBLED_NUM 32 

// RGB
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK

#undef RGBLIGHT_ANIMATIONS

#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
//#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
//#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_TWINKLE
